#!/bin/bash

# graphe : IPv6

# créer les namespaces pour les hôtes
ip netns add h1

# créer le switch
ovs-vsctl add-br bridge_ipv6
sudo sysctl -w net.ipv6.conf.bridge_ipv6.accept_ra=2

# créer les liens
ip link add h1-eth0 type veth peer name switchipv6-h1
ip link add switchipv6 type veth peer name switchipv6-host

# accrocher les liens aux namespaces
ip link set h1-eth0 netns h1

# connecter les liens au switch
ovs-vsctl add-port bridge_ipv6 switchipv6-h1
ovs-vsctl add-port bridge_ipv6 switchipv6-host

# activer les interfaces du namespace root
ip link set dev switchipv6-host up
ip link set dev switchipv6 up
ip link set dev switchipv6-h1 up

ip link set dev lo up

# activer les interfaces des namespaces h1 et h2 
ip netns exec h1 ip link set dev h1-eth0 up

ip netns exec h1 ip link set dev lo up



